theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true

params:
  plausible: noscrollday.fr
  posts:
    index:
      show_categories: false
      show_author: false
      truncate_description: 200 # Set to 0 to disable truncate
      layout: grid # grid | list